/* Generated by caretc 0.1.0 - do not edit by hand. */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdarg.h>
#include <stdio.h>

typedef char char32_t_alias_for_compat; /* placeholder */
typedef uint32_t ccaret_char;

typedef struct ccaret_string {
    const char* data;
    size_t      len;
} ccaret_string;

static inline ccaret_string ccaret_string_lit(const char* s) {
    ccaret_string r = { s, 0 };
    while (s[r.len]) ++r.len;
    return r;
}
#define CSTR(s) ((ccaret_string){ (s), sizeof(s) - 1 })

/* ccaret_print: variadic dispatcher for `print()` builtin. */
static void ccaret_print_s(ccaret_string s) {
    fwrite(s.data, 1, s.len, stdout);
}

int32_t main(void);
uint8_t add(uint8_t a, uint8_t b);
void greet(void);
int32_t add3(int32_t a, int32_t b, int32_t c);
int32_t next_id(void);

int32_t counter = 0;

int32_t main(void)     {
        printf("Hello, World! %d\n", 42);
    }

uint8_t add(uint8_t a, uint8_t b)     {
        return (a + b);
    }

void greet(void)     {
        printf("Hi from greet\n");
    }

int32_t add3(int32_t a, int32_t b, int32_t c)     {
        int32_t sum = ((a + b) + c);
        return sum;
    }

int32_t next_id(void)     {
        counter = (counter + 1);
        return counter;
    }

