/* Generated by caretc 0.1.0 - do not edit by hand. */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdarg.h>
#include <stdio.h>

typedef char char32_t_alias_for_compat; /* placeholder */
typedef uint32_t ccaret_char;

typedef struct ccaret_string {
    const char* data;
    size_t      len;
} ccaret_string;

static inline ccaret_string ccaret_string_lit(const char* s) {
    ccaret_string r = { s, 0 };
    while (s[r.len]) ++r.len;
    return r;
}
#define CSTR(s) ((ccaret_string){ (s), sizeof(s) - 1 })

/* ccaret_print: variadic dispatcher for `print()` builtin. */
static void ccaret_print_s(ccaret_string s) {
    fwrite(s.data, 1, s.len, stdout);
}

int32_t main(void);

ccaret_string name = CSTR("Prathmesh");
uint8_t age = 17;
const ccaret_string surname = CSTR("Barot");
const int32_t MAX = 65535;
const double PI = 3.14;
const bool YES = true;

int32_t main(void)     {
        printf("%s %s age=%d\n", name.data, surname.data, age);
        age = 18;
        printf("now age=%d, max=%d, pi=%f\n", age, MAX, PI);
        if (YES)         {
            return 0;
        }
        return 1;
    }

