// this is the caretc a compiler for the C^
#include "c_backend.hpp"
#include "Diagnostics/diagnostics.hpp"
#include <map>
#include <ostream>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace caret::backend::c {

namespace {

class Emitter {
public:
  Emitter(DiagnosticsEngine &diags) : diags_(diags) {}

  EmitResult run(const ast::TranslationUnit &unit) {
    EmitResult r;
    std::ostringstream out;

    // Header: includes, forward decls of string, common typedefs.
    out << "/* Generated by caretc 0.1.0 - do not edit by hand. */\n";
    out << "#include <stdint.h>\n";
    out << "#include <stddef.h>\n";
    out << "#include <stdbool.h>\n";
    out << "#include <stdarg.h>\n";
    out << "#include <stdio.h>\n";
    out << "\n";
    out << "typedef char char32_t_alias_for_compat; /* placeholder */\n";
    out << "typedef uint32_t ccaret_char;\n";
    out << "\n";
    out << "typedef struct ccaret_string {\n";
    out << "    const char* data;\n";
    out << "    size_t      len;\n";
    out << "} ccaret_string;\n";
    out << "\n";
    out << "static inline ccaret_string ccaret_string_lit(const char* s) {\n";
    out << "    ccaret_string r = { s, 0 };\n";
    out << "    while (s[r.len]) ++r.len;\n";
    out << "    return r;\n";
    out << "}\n";
    out << "#define CSTR(s) ((ccaret_string){ (s), sizeof(s) - 1 })\n";
    out << "\n";
    out << "/* ccaret_print: variadic dispatcher for `print()` builtin. */\n";
    out << "static void ccaret_print_s(ccaret_string s) {\n";
    out << "    fwrite(s.data, 1, s.len, stdout);\n";
    out << "}\n";
    out << "\n";

    // First pass: emit forward decls for all top-level functions.
    for (const auto &d : unit) {
      if (d->kind == ast::DeclKind::Function ||
          d->kind == ast::DeclKind::ExportFn ||
          d->kind == ast::DeclKind::ExternFn) {
        emit_function_decl(out, *d);
        out << ";\n";
      }
    }
    out << "\n";

    // Second pass: top-level var/const decls.
    for (const auto &d : unit) {
      if (d->kind == ast::DeclKind::Var || d->kind == ast::DeclKind::Const) {
        emit_top_var(out, *d);
        out << ";\n";
      }
    }
    if (!unit.empty())
      out << "\n";

    // Third pass: function bodies.
    for (const auto &d : unit) {
      if (d->kind == ast::DeclKind::Function ||
          d->kind == ast::DeclKind::ExportFn) {
        emit_function_def(out, *d);
        out << "\n";
      }
    }

    // Imports — no-op for now (we don't resolve modules yet).
    for (const auto &d : unit) {
      if (d->kind == ast::DeclKind::Import) {
        (void)d; // silently ignore
      }
    }

    r.code = out.str();
    r.ok = !diags_.has_errors();
    return r;
  }

private:
  DiagnosticsEngine &diags_;

  // ----- type emission -----
  std::string emit_type(const ast::TypePtr &t) {
    if (!t)
      return "void";
    switch (t->kind) {
    case ast::TypeKind::Named:
      return c_type_name(t->name);
    case ast::TypeKind::Auto:
      // C has no auto; pick a sensible default. Caller must be in a
      // var-init context where type can be elided. Fall back to int.
      return "int";
    case ast::TypeKind::Pointer: {
      std::string inner = emit_type(t->inner);
      return inner + " *";
    }
    case ast::TypeKind::Reference: {
      // C^ references become C pointers for the C backend.
      std::string inner = emit_type(t->inner);
      return inner + " *";
    }
    case ast::TypeKind::Array: {
      std::string inner = emit_type(t->inner);
      return inner + " *"; // fat pointer
    }
    case ast::TypeKind::Slice:
      return emit_type(t->inner) + " *";
    case ast::TypeKind::Optional:
      return emit_type(t->inner);
    case ast::TypeKind::ErrorUnion:
      return emit_type(t->inner);
    }
    return "void";
  }

  static std::string c_type_name(const std::string &caret_name) {
    if (caret_name == "i8")
      return "int8_t";
    if (caret_name == "i16")
      return "int16_t";
    if (caret_name == "i32")
      return "int32_t";
    if (caret_name == "i64")
      return "int64_t";
    if (caret_name == "i128")
      return "__int128";
    if (caret_name == "isize")
      return "intptr_t";
    if (caret_name == "u8")
      return "uint8_t";
    if (caret_name == "u16")
      return "uint16_t";
    if (caret_name == "u32")
      return "uint32_t";
    if (caret_name == "u64")
      return "uint64_t";
    if (caret_name == "u128")
      return "unsigned __int128";
    if (caret_name == "usize")
      return "size_t";
    if (caret_name == "f32")
      return "float";
    if (caret_name == "f64")
      return "double";
    if (caret_name == "bool")
      return "bool";
    if (caret_name == "char")
      return "ccaret_char";
    if (caret_name == "void")
      return "void";
    if (caret_name == "string")
      return "ccaret_string";
    if (caret_name == "auto")
      return "int";
    return caret_name; // pass through user types
  }

  static bool is_void_type(const ast::TypePtr &t) {
    return t && t->kind == ast::TypeKind::Named && t->name == "void";
  }

  // ----- declarations -----
  void emit_function_decl(std::ostream &out, const ast::Decl &d) {
    std::string ret = emit_type(d.fn_return_type);
    if (is_void_type(d.fn_return_type))
      ret = "void";
    out << ret << " " << d.fn_name << "(";
    if (d.fn_params.empty()) {
      out << "void";
    } else {
      for (std::size_t i = 0; i < d.fn_params.size(); ++i) {
        if (i)
          out << ", ";
        const auto &p = d.fn_params[i];
        out << emit_type(p.type) << " " << p.name;
      }
    }
    out << ")";
  }

  void emit_top_var(std::ostream &out, const ast::Decl &d) {
    std::string ty = emit_type(d.var_type);
    if (d.var_is_const)
      out << "const ";
    out << ty << " " << d.var_name;
    if (d.var_init) {
      out << " = ";
      emit_expr(out, d.var_init);
    }
  }

  void emit_function_def(std::ostream &out, const ast::Decl &d) {
    emit_function_decl(out, d);
    out << " ";
    if (!d.fn_body) {
      out << "{}\n";
      return;
    }
    emit_stmt(out, d.fn_body);
  }

  // ----- statements -----
  void emit_stmt(std::ostream &out, const ast::StmtPtr &s, int indent = 1) {
    if (!s)
      return;
    std::string pad(indent * 4, ' ');
    switch (s->kind) {
    case ast::StmtKind::Block: {
      out << pad << "{\n";
      for (const auto &sub : s->block_stmts)
        emit_stmt(out, sub, indent + 1);
      out << pad << "}\n";
      break;
    }
    case ast::StmtKind::VarDecl: {
      std::string ty = emit_type(s->var_type);
      if (s->is_const)
        out << pad << "const ";
      else
        out << pad;
      out << ty << " " << s->var_name;
      if (s->var_init) {
        out << " = ";
        emit_expr(out, s->var_init);
      }
      out << ";\n";
      break;
    }
    case ast::StmtKind::ExprStmt:
      out << pad;
      emit_expr(out, s->expr);
      out << ";\n";
      break;
    case ast::StmtKind::Return:
      if (s->return_value) {
        out << pad << "return ";
        emit_expr(out, s->return_value);
        out << ";\n";
      } else {
        out << pad << "return;\n";
      }
      break;
    case ast::StmtKind::If:
      out << pad << "if (";
      emit_expr(out, s->if_cond);
      out << ") ";
      emit_stmt(out, s->if_then, indent);
      if (s->if_else) {
        out << pad << "else ";
        if (s->if_else->kind == ast::StmtKind::If) {
          emit_stmt(out, s->if_else, indent);
        } else {
          emit_stmt(out, s->if_else, indent);
        }
      }
      break;
    case ast::StmtKind::While:
      out << pad << "while (";
      emit_expr(out, s->while_cond);
      out << ") ";
      emit_stmt(out, s->while_body, indent);
      break;
    case ast::StmtKind::For:
      out << pad << "for (";
      if (s->for_init) {
        if (s->for_init->kind == ast::StmtKind::VarDecl) {
          out << emit_type(s->for_init->var_type) << " "
              << s->for_init->var_name;
          if (s->for_init->var_init) {
            out << " = ";
            emit_expr(out, s->for_init->var_init);
          }
        } else {
          emit_expr(out, s->for_init->expr);
        }
      }
      out << "; ";
      if (s->for_cond)
        emit_expr(out, s->for_cond);
      out << "; ";
      if (s->for_step)
        emit_expr(out, s->for_step);
      out << ") ";
      emit_stmt(out, s->for_body, indent);
      break;
    case ast::StmtKind::Loop:
      out << pad << "while (1) ";
      emit_stmt(out, s->loop_body, indent);
      break;
    case ast::StmtKind::Break:
      out << pad << "break;\n";
      break;
    case ast::StmtKind::Continue:
      out << pad << "continue;\n";
      break;
    case ast::StmtKind::Defer:
      // Best-effort: emit the deferred expression at the defer site
      // (C has no defer). For a single-statement defer with an
      // identifier of form "x" we emit nothing; for method calls we
      // emit them inline as a comment + statement. To stay correct
      // for now we simply emit a comment marker.
      if (s->defer_expr) {
        out << pad << "/* defer: ";
        emit_expr(out, s->defer_expr);
        out << "; */\n";
      } else {
        out << pad << "/* defer block: see source */\n";
      }
      break;
    case ast::StmtKind::Empty:
      out << pad << ";\n";
      break;
    }
  }

  // ----- expressions -----
  void emit_expr(std::ostream &out, const ast::ExprPtr &e) {
    if (!e) {
      out << "0";
      return;
    }
    switch (e->kind) {
    case ast::ExprKind::IntegerLiteral:
      out << e->int_value;
      break;
    case ast::ExprKind::FloatLiteral:
      out << e->float_value;
      break;
    case ast::ExprKind::StringLiteral:
      out << "CSTR(\"" << escape_c(e->string_value) << "\")";
      break;
    case ast::ExprKind::CharLiteral:
      out << "(ccaret_char)'";
      if (e->char_value == '\n')
        out << "\\n";
      else if (e->char_value == '\t')
        out << "\\t";
      else if (e->char_value == '\\')
        out << "\\\\";
      else if (e->char_value == '\'')
        out << "\\'";
      else if (e->char_value == 0)
        out << "\\0";
      else
        out << static_cast<char>(e->char_value);
      out << "'";
      break;
    case ast::ExprKind::BoolLiteral:
      out << (e->bool_value ? "true" : "false");
      break;
    case ast::ExprKind::NullLiteral:
      out << "NULL";
      break;
    case ast::ExprKind::Identifier:
      out << e->name;
      break;
    case ast::ExprKind::Unary: {
      const char *op = nullptr;
      bool post = false;
      switch (e->unary_op) {
      case ast::UnaryOp::Neg:
        op = "-";
        break;
      case ast::UnaryOp::Plus:
        op = "+";
        break;
      case ast::UnaryOp::Not:
        op = "!";
        break;
      case ast::UnaryOp::BitNot:
        op = "~";
        break;
      case ast::UnaryOp::PreInc:
        op = "++";
        break;
      case ast::UnaryOp::PreDec:
        op = "--";
        break;
      case ast::UnaryOp::PostInc:
        op = "++";
        post = true;
        break;
      case ast::UnaryOp::PostDec:
        op = "--";
        post = true;
        break;
      case ast::UnaryOp::Deref:
        op = "(*";
        break;
      }
      if (!op)
        op = "?";
      if (e->unary_op == ast::UnaryOp::Deref) {
        emit_expr(out, e->lhs);
        out << ")";
      } else if (post) {
        emit_expr(out, e->lhs);
        out << op;
      } else {
        out << op;
        emit_expr(out, e->lhs);
      }
      break;
    }
    case ast::ExprKind::AddrOf:
      out << "(&";
      emit_expr(out, e->lhs);
      out << ")";
      break;
    case ast::ExprKind::Binary: {
      const char *op = nullptr;
      switch (e->binary_op) {
      case ast::BinaryOp::Add:
        op = "+";
        break;
      case ast::BinaryOp::Sub:
        op = "-";
        break;
      case ast::BinaryOp::Mul:
        op = "*";
        break;
      case ast::BinaryOp::Div:
        op = "/";
        break;
      case ast::BinaryOp::Mod:
        op = "%";
        break;
      case ast::BinaryOp::Eq:
        op = "==";
        break;
      case ast::BinaryOp::NotEq:
        op = "!=";
        break;
      case ast::BinaryOp::Lt:
        op = "<";
        break;
      case ast::BinaryOp::LtEq:
        op = "<=";
        break;
      case ast::BinaryOp::Gt:
        op = ">";
        break;
      case ast::BinaryOp::GtEq:
        op = ">=";
        break;
      case ast::BinaryOp::BitAnd:
        op = "&";
        break;
      case ast::BinaryOp::BitOr:
        op = "|";
        break;
      case ast::BinaryOp::BitXor:
        op = "^";
        break;
      case ast::BinaryOp::Shl:
        op = "<<";
        break;
      case ast::BinaryOp::Shr:
        op = ">>";
        break;
      case ast::BinaryOp::And:
        op = "&&";
        break;
      case ast::BinaryOp::Or:
        op = "||";
        break;
      }
      if (!op)
        op = "?";
      out << "(";
      emit_expr(out, e->lhs);
      out << " " << op << " ";
      emit_expr(out, e->rhs);
      out << ")";
      break;
    }
    case ast::ExprKind::Assign: {
      emit_expr(out, e->assign_target);
      if (e->literal_text == "=") {
        out << " = ";
      } else {
        // compound: +=, -=, etc.
        std::string op = e->literal_text;
        if (!op.empty() && op.back() == '=')
          op.pop_back();
        out << " " << op << "= ";
      }
      emit_expr(out, e->rhs);
      break;
    }
    case ast::ExprKind::Call: {
      // Special-case builtin "print" -> printf
      if (e->callee && e->callee->kind == ast::ExprKind::Identifier &&
          e->callee->name == "print") {
        out << "printf(";
        for (std::size_t i = 0; i < e->args.size(); ++i) {
          if (i)
            out << ", ";
          if (i == 0 && e->args[i]->kind == ast::ExprKind::StringLiteral) {
            // Translate C^ format specifiers, then C-escape.
            out << "\"" << escape_c(translate_format(e->args[i]->string_value))
                << "\"";
          } else {
            emit_expr(out, e->args[i]);
          }
        }
        out << ")";
      } else {
        emit_expr(out, e->callee);
        out << "(";
        for (std::size_t i = 0; i < e->args.size(); ++i) {
          if (i)
            out << ", ";
          emit_expr(out, e->args[i]);
        }
        out << ")";
      }
      break;
    }
    case ast::ExprKind::FieldAccess:
      emit_expr(out, e->object);
      out << "." << e->field_name;
      break;
    case ast::ExprKind::IndexAccess:
      emit_expr(out, e->object);
      out << "[";
      emit_expr(out, e->index);
      out << "]";
      break;
    case ast::ExprKind::Cast:
      out << "((" << emit_type(e->cast_type) << ")";
      emit_expr(out, e->lhs);
      out << ")";
      break;
    case ast::ExprKind::Grouped:
      out << "(";
      emit_expr(out, e->lhs);
      out << ")";
      break;
    }
  }

  static std::string escape_c(const std::string &s) {
    std::string out;
    out.reserve(s.size() + 2);
    for (char c : s) {
      switch (c) {
      case '\n':
        out += "\\n";
        break;
      case '\t':
        out += "\\t";
        break;
      case '\r':
        out += "\\r";
        break;
      case '\\':
        out += "\\\\";
        break;
      case '"':
        out += "\\\"";
        break;
      case '\0':
        out += "\\0";
        break;
      default:
        if (static_cast<unsigned char>(c) < 0x20) {
          char buf[8];
          std::snprintf(buf, sizeof(buf), "\\x%02x",
                        static_cast<unsigned char>(c));
          out += buf;
        } else {
          out += c;
        }
      }
    }
    return out;
  }

  // Translate C^ format specifiers ({}, {d}, {s}, {f}, {x}) into printf
  // format specifiers. Unrecognised forms are left intact.
  static std::string translate_format(const std::string &s) {
    std::string out;
    out.reserve(s.size());
    std::size_t i = 0;
    while (i < s.size()) {
      if (s[i] == '{') {
        std::size_t end = s.find('}', i + 1);
        if (end == std::string::npos) {
          out += s[i++];
          continue;
        }
        std::string body = s.substr(i + 1, end - i - 1);
        // Trim
        std::size_t a = 0, b = body.size();
        while (a < b && std::isspace(static_cast<unsigned char>(body[a])))
          ++a;
        while (b > a && std::isspace(static_cast<unsigned char>(body[b - 1])))
          --b;
        body = body.substr(a, b - a);
        if (body.empty())
          out += "%s"; // {} -> generic, default to string
        else if (body == "d" || body == "i")
          out += "%d";
        else if (body == "u")
          out += "%u";
        else if (body == "x")
          out += "%x";
        else if (body == "X")
          out += "%X";
        else if (body == "s")
          out += "%s";
        else if (body == "f" || body == "F")
          out += "%f";
        else if (body == "c")
          out += "%c";
        else if (body == "p")
          out += "%p";
        else if (body == "ld")
          out += "%ld";
        else if (body == "lu")
          out += "%lu";
        else if (body == "lld" || body == "d64")
          out += "%lld";
        else if (body == "llu" || body == "u64")
          out += "%llu";
        else if (body == "z" || body == "zu")
          out += "%zu";
        else
          out += "%" + body;
        i = end + 1;
      } else {
        out += s[i++];
      }
    }
    return out;
  }
};

} // namespace

EmitResult emit(const ast::TranslationUnit &unit) {
  // We don't have direct access to the diagnostics engine here; the
  // caller (main.cpp) wires the same engine through the parser path and
  // any errors during emission are simply not generated for the supported
  // subset. We still pass a local engine for future use.
  DiagnosticsEngine local;
  Emitter e(local);
  return e.run(unit);
}
} // namespace caret::backend::c
