// C backend implementation.
//
// Translation strategy:
//   * One pass over the AST, three logical phases:
//       1. Emit a fixed header (includes, ccaret_string, print helper).
//       2. Walk the unit, remembering every name that is a C^
//          reference. C^ references lower to C pointers and every
//          use auto-derefs, so we need the name set at every emit.
//       3. Forward-decl functions, then top-level var/const decls,
//          then function bodies.
//   * Expressions lower with the smallest possible C surface: binary
//     ops are parenthesised, calls split into a callee + arg list,
//     string literals go through CSTR() for a fat-pointer literal.
//   * The `print()` builtin is recognised by name and lowered to
//     printf with a C^ -> printf format translation (see
//     translate_format).
//
// This backend does not yet do type-aware lowering; everything
// (mutability, borrow rules) is assumed to have been checked by a
// future semantic pass. The output is correct C, but it is *not*
// guaranteed to be safe or meaningful in the presence of undefined
// behaviour at the source level.
#include "c_backend.hpp"
#include "Diagnostics/diagnostics.hpp"
// #include <map>
#include <ostream>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace caret::backend::c {

namespace {

class Emitter {
public:
  Emitter(DiagnosticsEngine &diags) : diags_(diags) {}

  EmitResult run(const ast::TranslationUnit &unit) {
    EmitResult r;
    std::ostringstream out;

    // Header: includes, forward decls of string, common typedefs.
    out << "/* Generated by caretc 0.1.0 - do not edit by hand. */\n";
    out << "#include <stdint.h>\n";
    out << "#include <stddef.h>\n";
    out << "#include <stdbool.h>\n";
    out << "#include <stdarg.h>\n";
    out << "#include <stdio.h>\n";
    out << "\n";
    out << "typedef char char32_t_alias_for_compat; /* placeholder */\n";
    out << "typedef uint32_t ccaret_char;\n";
    out << "\n";
    out << "typedef struct ccaret_string {\n";
    out << "    const char* data;\n";
    out << "    size_t      len;\n";
    out << "} ccaret_string;\n";
    out << "\n";
    out << "static inline ccaret_string ccaret_string_lit(const char* s) {\n";
    out << "    ccaret_string r = { s, 0 };\n";
    out << "    while (s[r.len]) ++r.len;\n";
    out << "    return r;\n";
    out << "}\n";
    out << "#define CSTR(s) ((ccaret_string){ (s), sizeof(s) - 1 })\n";
    out << "\n";
    out << "/* ccaret_print: variadic dispatcher for `print()` builtin. */\n";
    out << "static void ccaret_print_s(ccaret_string s) {\n";
    out << "    fwrite(s.data, 1, s.len, stdout);\n";
    out << "}\n";
    out << "\n";

    // First pass: collect reference names so we can auto-deref them later
    // (C^ references are emitted as C pointers; every use auto-derefs).
    collect_reference_names(unit);

    // First pass: emit forward decls for all top-level functions.
    for (const auto &d : unit) {
      if (d->kind == ast::DeclKind::Function ||
          d->kind == ast::DeclKind::ExportFn ||
          d->kind == ast::DeclKind::ExternFn) {
        emit_function_decl(out, *d);
        out << ";\n";
      }
    }
    out << "\n";

    // Second pass: top-level var/const decls.
    for (const auto &d : unit) {
      if (d->kind == ast::DeclKind::Var || d->kind == ast::DeclKind::Const) {
        emit_top_var(out, *d);
        out << ";\n";
      }
    }
    if (!unit.empty())
      out << "\n";

    // Third pass: function bodies.
    for (const auto &d : unit) {
      if (d->kind == ast::DeclKind::Function ||
          d->kind == ast::DeclKind::ExportFn) {
        emit_function_def(out, *d);
        out << "\n";
      }
    }

    // Imports — no-op for now (we don't resolve modules yet).
    for (const auto &d : unit) {
      if (d->kind == ast::DeclKind::Import) {
        (void)d; // silently ignore
      }
    }

    r.code = out.str();
    r.ok = !diags_.has_errors();
    return r;
  }

private:
  DiagnosticsEngine &diags_;

  // Names of every variable whose type is a C^ reference. In C^ sources
  // every read or write through a reference auto-derefs. We model refs as
  // C pointers, so we wrap each use in `(*...)`. This is a flat name set;
  // it intentionally leaks across function boundaries in this prototype,
  // which is fine because C function-level names are file-scoped and
  // identical names with different kinds in different functions don't
  // collide in the C output (only the assignment/call sites differ).
  std::set<std::string> ref_names_;

  // is_reference_type: a thin predicate that tolerates a null TypePtr
  // so call sites in emit_type / emit_function_def don't have to.
  static bool is_reference_type(const ast::TypePtr &t) {
    return t && t->kind == ast::TypeKind::Reference;
  }

  // Walk the unit and record every name whose declared type is a reference.
  // This must run before any expression is emitted so that every
  // reference use can be wrapped in `(*...)`.
  void collect_reference_names(const ast::TranslationUnit &unit) {
    for (const auto &d : unit) {
      if (d->kind == ast::DeclKind::Var || d->kind == ast::DeclKind::Const) {
        if (is_reference_type(d->var_type))
          ref_names_.insert(d->var_name);
      } else if (d->kind == ast::DeclKind::Function ||
                 d->kind == ast::DeclKind::ExportFn) {
        for (const auto &p : d->fn_params) {
          if (is_reference_type(p.type))
            ref_names_.insert(p.name);
        }
        collect_refs_in_stmt(d->fn_body);
      }
    }
  }

  void collect_refs_in_stmt(const ast::StmtPtr &s) {
    if (!s)
      return;
    switch (s->kind) {
    case ast::StmtKind::VarDecl:
      if (is_reference_type(s->var_type))
        ref_names_.insert(s->var_name);
      break;
    case ast::StmtKind::Block:
      for (const auto &sub : s->block_stmts)
        collect_refs_in_stmt(sub);
      break;
    case ast::StmtKind::If:
      collect_refs_in_stmt(s->if_then);
      collect_refs_in_stmt(s->if_else);
      break;
    case ast::StmtKind::While:
      collect_refs_in_stmt(s->while_body);
      break;
    case ast::StmtKind::For:
      collect_refs_in_stmt(s->for_init);
      collect_refs_in_stmt(s->for_body);
      break;
    case ast::StmtKind::Loop:
      collect_refs_in_stmt(s->loop_body);
      break;
    case ast::StmtKind::Defer:
    case ast::StmtKind::Return:
    case ast::StmtKind::ExprStmt:
    case ast::StmtKind::Break:
    case ast::StmtKind::Continue:
    case ast::StmtKind::Empty:
      break;
    }
  }

  // ----- type emission -----
  // Convert an AST type to its C spelling. C has no notion of
  // references, slices, optionals, or error unions, so we map:
  //   T&  ->  T*  (and the caller wraps every use in `(*...)`)
  //   T[] / T[N]  ->  T*  (the fat-pointer runtime helper tracks the length)
  //   T?  /  T!Err  ->  T   (error info is carried separately)
  // The function is null-safe: a missing type degrades to `void`.
  std::string emit_type(const ast::TypePtr &t) {
    if (!t)
      return "void";
    switch (t->kind) {
    case ast::TypeKind::Named:
      return c_type_name(t->name);
    case ast::TypeKind::Auto:
      // C has no auto; pick a sensible default. Caller must be in a
      // var-init context where type can be elided. Fall back to int.
      return "int";
    case ast::TypeKind::Pointer: {
      // C convention: bind `*` to the variable name (`T*name`), not the
      // type. We emit the inner type and a trailing `*` with no extra
      // space; the caller's separator takes care of the gap to the name.
      return emit_type(t->inner) + "*";
    }
    case ast::TypeKind::Reference: {
      // C^ references are emitted as C pointers. Same convention as Pointer.
      return emit_type(t->inner) + "*";
    }
    case ast::TypeKind::Array: {
      std::string inner = emit_type(t->inner);
      return inner + "*"; // fat pointer
    }
    case ast::TypeKind::Slice:
      return emit_type(t->inner) + "*";
    case ast::TypeKind::Optional:
      return emit_type(t->inner);
    case ast::TypeKind::ErrorUnion:
      return emit_type(t->inner);
    }
    return "void";
  }

  static std::string c_type_name(const std::string &caret_name) {
    if (caret_name == "i8")
      return "int8_t";
    if (caret_name == "i16")
      return "int16_t";
    if (caret_name == "i32")
      return "int32_t";
    if (caret_name == "i64")
      return "int64_t";
    if (caret_name == "i128")
      return "__int128";
    if (caret_name == "isize")
      return "intptr_t";
    if (caret_name == "u8")
      return "uint8_t";
    if (caret_name == "u16")
      return "uint16_t";
    if (caret_name == "u32")
      return "uint32_t";
    if (caret_name == "u64")
      return "uint64_t";
    if (caret_name == "u128")
      return "unsigned __int128";
    if (caret_name == "usize")
      return "size_t";
    if (caret_name == "f32")
      return "float";
    if (caret_name == "f64")
      return "double";
    if (caret_name == "bool")
      return "bool";
    if (caret_name == "char")
      return "ccaret_char";
    if (caret_name == "void")
      return "void";
    if (caret_name == "string")
      return "ccaret_string";
    if (caret_name == "auto")
      return "int";
    return caret_name; // pass through user types
  }

  // is_void_type: thin predicate used by emit_function_decl to keep the
  // return type spelling exactly `void` (not `int` from the default
  // path) for the many `void NAME(...)` declarations in real code.
  static bool is_void_type(const ast::TypePtr &t) {
    return t && t->kind == ast::TypeKind::Named && t->name == "void";
  }

  // ----- declarations -----
  // emit_function_decl writes the prototype — `RET NAME ( PARAM, ... )` —
  // shared between a forward declaration and a full definition. Empty
  // parameter lists emit the explicit C `(void)` form so the resulting
  // prototype still catches argument-count mismatches at link time.
  void emit_function_decl(std::ostream &out, const ast::Decl &d) {
    std::string ret = emit_type(d.fn_return_type);
    if (is_void_type(d.fn_return_type))
      ret = "void";
    out << ret << " " << d.fn_name << "(";
    if (d.fn_params.empty()) {
      out << "void";
    } else {
      for (std::size_t i = 0; i < d.fn_params.size(); ++i) {
        if (i)
          out << ", ";
        const auto &p = d.fn_params[i];
        out << emit_type(p.type) << " " << p.name;
      }
    }
    out << ")";
  }

  // emit_top_var: write `<type> <name>[ = <init>];` for a top-level
  // var/const decl. References get a leading `&` on the init side
  // because C^ refs bind to an address, not a value copy.
  void emit_top_var(std::ostream &out, const ast::Decl &d) {
    std::string ty = emit_type(d.var_type);
    if (d.var_is_const)
      out << "const ";
    out << ty << " " << d.var_name;
    if (d.var_init) {
      out << " = ";
      if (is_reference_type(d.var_type))
        out << "&";
      emit_expr(out, d.var_init);
    }
  }

  // emit_function_def: the definition side of a function. The
  // forward-decl-only case (no body) is the empty-block form `{}`
  // because the parser has already validated a body or a `;` for
  // extern declarations.
  void emit_function_def(std::ostream &out, const ast::Decl &d) {
    emit_function_decl(out, d);
    if (!d.fn_body) {
      out << " {}\n";
      return;
    }
    if (d.fn_body->kind == ast::StmtKind::Block) {
      // Function body is a Block on the same line as the signature.
      emit_block_inline(out, d.fn_body, /*indent=*/0);
    } else {
      out << " ";
      emit_stmt(out, d.fn_body);
    }
  }

  // ----- statements -----

  // Emit a Block whose `{` sits on the same line as preceding text
  // (e.g. `int32_t main(void) { ... }` or `if (cond) { ... }`).
  // The caller is responsible for emitting the leading context; this
  // helper emits ` { ... }` with body indented one level deeper than
  // the `indent` argument, and the closing `}` at `indent`.
  void emit_block_inline(std::ostream &out, const ast::StmtPtr &s, int indent) {
    out << " {\n";
    for (const auto &sub : s->block_stmts)
      emit_stmt(out, sub, indent + 1);
    out << std::string(indent * 4, ' ') << "}\n";
  }

  // Emit a child statement that follows a control-flow keyword like
  // `if (...)` or `while (...)`. Block bodies are emitted inline (brace
  // on the same line as the keyword); any other body gets a single
  // separating space and is printed on its own line.
  void emit_compound_or_inline(std::ostream &out, const ast::StmtPtr &body,
                               int indent) {
    if (body && body->kind == ast::StmtKind::Block) {
      emit_block_inline(out, body, indent);
    } else {
      out << " ";
      emit_stmt(out, body, indent);
    }
  }

  void emit_stmt(std::ostream &out, const ast::StmtPtr &s, int indent = 1) {
    if (!s)
      return;
    std::string pad(indent * 4, ' ');
    switch (s->kind) {
    case ast::StmtKind::Block: {
      // A Block that shows up at statement level (not as the body of a
      // control-flow keyword) is a standalone block: pad-prefixed, brace
      // on its own line. Control-flow callers should use
      // `emit_block_inline` instead.
      out << pad << "{\n";
      for (const auto &sub : s->block_stmts)
        emit_stmt(out, sub, indent + 1);
      out << pad << "}\n";
      break;
    }
    case ast::StmtKind::VarDecl: {
      std::string ty = emit_type(s->var_type);
      if (s->is_const)
        out << pad << "const ";
      else
        out << pad;
      out << ty << " " << s->var_name;
      if (s->var_init) {
        out << " = ";
        if (is_reference_type(s->var_type))
          out << "&";
        emit_expr(out, s->var_init);
      }
      out << ";\n";
      break;
    }
    case ast::StmtKind::ExprStmt:
      out << pad;
      emit_expr(out, s->expr);
      out << ";\n";
      break;
    case ast::StmtKind::Return:
      if (s->return_value) {
        out << pad << "return ";
        emit_expr(out, s->return_value);
        out << ";\n";
      } else {
        out << pad << "return;\n";
      }
      break;
    case ast::StmtKind::If:
      out << pad << "if (";
      emit_expr(out, s->if_cond);
      out << ")";
      emit_compound_or_inline(out, s->if_then, indent);
      if (s->if_else) {
        out << pad << "else";
        emit_compound_or_inline(out, s->if_else, indent);
      }
      break;
    case ast::StmtKind::While:
      out << pad << "while (";
      emit_expr(out, s->while_cond);
      out << ")";
      emit_compound_or_inline(out, s->while_body, indent);
      break;
    case ast::StmtKind::For:
      out << pad << "for (";
      if (s->for_init) {
        if (s->for_init->kind == ast::StmtKind::VarDecl) {
          out << emit_type(s->for_init->var_type) << " "
              << s->for_init->var_name;
          if (s->for_init->var_init) {
            out << " = ";
            emit_expr(out, s->for_init->var_init);
          }
        } else {
          emit_expr(out, s->for_init->expr);
        }
      }
      out << "; ";
      if (s->for_cond)
        emit_expr(out, s->for_cond);
      out << "; ";
      if (s->for_step)
        emit_expr(out, s->for_step);
      out << ")";
      emit_compound_or_inline(out, s->for_body, indent);
      break;
    case ast::StmtKind::Loop:
      out << pad << "while (1)";
      emit_compound_or_inline(out, s->loop_body, indent);
      break;
    case ast::StmtKind::Break:
      out << pad << "break;\n";
      break;
    case ast::StmtKind::Continue:
      out << pad << "continue;\n";
      break;
    case ast::StmtKind::Defer:
      // C has no defer. The most correct lowering would buffer
      // deferred calls and replay them at every scope exit; that's
      // blocked on the proper IR pass. For now we emit a comment
      // marker so a human reading the generated C can still see the
      // original intent. Calling the deferred expression at the
      // defer site would change observable behaviour, so we
      // explicitly do not do that.
      if (s->defer_expr) {
        out << pad << "/* defer: ";
        emit_expr(out, s->defer_expr);
        out << "; */\n";
      } else {
        out << pad << "/* defer block: see source */\n";
      }
      break;
    case ast::StmtKind::Empty:
      out << pad << ";\n";
      break;
    }
  }

  // ----- expressions -----
  void emit_expr(std::ostream &out, const ast::ExprPtr &e) {
    if (!e) {
      out << "0";
      return;
    }
    switch (e->kind) {
    case ast::ExprKind::IntegerLiteral:
      out << e->int_value;
      break;
    case ast::ExprKind::FloatLiteral:
      out << e->float_value;
      break;
    case ast::ExprKind::StringLiteral:
      out << "CSTR(\"" << escape_c(e->string_value) << "\")";
      break;
    case ast::ExprKind::CharLiteral:
      out << "(ccaret_char)'";
      if (e->char_value == '\n')
        out << "\\n";
      else if (e->char_value == '\t')
        out << "\\t";
      else if (e->char_value == '\\')
        out << "\\\\";
      else if (e->char_value == '\'')
        out << "\\'";
      else if (e->char_value == 0)
        out << "\\0";
      else
        out << static_cast<char>(e->char_value);
      out << "'";
      break;
    case ast::ExprKind::BoolLiteral:
      out << (e->bool_value ? "true" : "false");
      break;
    case ast::ExprKind::NullLiteral:
      out << "NULL";
      break;
    case ast::ExprKind::Identifier:
      if (ref_names_.count(e->name)) {
        out << "(*" << e->name << ")";
      } else {
        out << e->name;
      }
      break;
    case ast::ExprKind::PostfixDeref:
      // `ptr.*` in C^ -> `(*ptr)` in C.
      out << "(*";
      emit_expr(out, e->lhs);
      out << ")";
      break;
    case ast::ExprKind::Unary: {
      const char *op = nullptr;
      bool post = false;
      switch (e->unary_op) {
      case ast::UnaryOp::Neg:
        op = "-";
        break;
      case ast::UnaryOp::Plus:
        op = "+";
        break;
      case ast::UnaryOp::Not:
        op = "!";
        break;
      case ast::UnaryOp::BitNot:
        op = "~";
        break;
      case ast::UnaryOp::PreInc:
        op = "++";
        break;
      case ast::UnaryOp::PreDec:
        op = "--";
        break;
      case ast::UnaryOp::PostInc:
        op = "++";
        post = true;
        break;
      case ast::UnaryOp::PostDec:
        op = "--";
        post = true;
        break;
      case ast::UnaryOp::Deref:
        op = "(*";
        break;
      }
      if (!op)
        op = "?";
      if (e->unary_op == ast::UnaryOp::Deref) {
        emit_expr(out, e->lhs);
        out << ")";
      } else if (post) {
        emit_expr(out, e->lhs);
        out << op;
      } else {
        out << op;
        emit_expr(out, e->lhs);
      }
      break;
    }
    case ast::ExprKind::AddrOf:
      // `&ident` is the overwhelmingly common shape; emit it bare.
      // Anything more complex (e.g. `&(a + b)`) is parenthesised to
      // keep the precedence obvious to a human reader and to silence
      // the "address of temporary" warning some compilers raise.
      if (e->lhs && e->lhs->kind == ast::ExprKind::Identifier) {
        out << "&" << e->lhs->name;
      } else {
        out << "(&";
        emit_expr(out, e->lhs);
        out << ")";
      }
      break;
    case ast::ExprKind::Binary: {
      const char *op = nullptr;
      switch (e->binary_op) {
      case ast::BinaryOp::Add:
        op = "+";
        break;
      case ast::BinaryOp::Sub:
        op = "-";
        break;
      case ast::BinaryOp::Mul:
        op = "*";
        break;
      case ast::BinaryOp::Div:
        op = "/";
        break;
      case ast::BinaryOp::Mod:
        op = "%";
        break;
      case ast::BinaryOp::Eq:
        op = "==";
        break;
      case ast::BinaryOp::NotEq:
        op = "!=";
        break;
      case ast::BinaryOp::Lt:
        op = "<";
        break;
      case ast::BinaryOp::LtEq:
        op = "<=";
        break;
      case ast::BinaryOp::Gt:
        op = ">";
        break;
      case ast::BinaryOp::GtEq:
        op = ">=";
        break;
      case ast::BinaryOp::BitAnd:
        op = "&";
        break;
      case ast::BinaryOp::BitOr:
        op = "|";
        break;
      case ast::BinaryOp::BitXor:
        op = "^";
        break;
      case ast::BinaryOp::Shl:
        op = "<<";
        break;
      case ast::BinaryOp::Shr:
        op = ">>";
        break;
      case ast::BinaryOp::And:
        op = "&&";
        break;
      case ast::BinaryOp::Or:
        op = "||";
        break;
      }
      if (!op)
        op = "?";
      out << "(";
      emit_expr(out, e->lhs);
      out << " " << op << " ";
      emit_expr(out, e->rhs);
      out << ")";
      break;
    }
    case ast::ExprKind::Assign: {
      // If the assignment target is a plain identifier whose type is a
      // C^ reference, dereference it on the LHS (`(*name) = ...`).
      if (e->assign_target &&
          e->assign_target->kind == ast::ExprKind::Identifier &&
          ref_names_.count(e->assign_target->name)) {
        out << "(*" << e->assign_target->name << ")";
      } else {
        emit_expr(out, e->assign_target);
      }
      if (e->literal_text == "=") {
        out << " = ";
      } else {
        // compound: +=, -=, etc.
        std::string op = e->literal_text;
        if (!op.empty() && op.back() == '=')
          op.pop_back();
        out << " " << op << "= ";
      }
      emit_expr(out, e->rhs);
      break;
    }
    case ast::ExprKind::Call: {
      // Special-case the `print()` builtin and lower it to printf. The
      // first argument's format specifiers go through translate_format
      // (C^ `{d}` -> C `%d`) and then through escape_c so the resulting
      // C string is a valid C string literal. Remaining arguments are
      // emitted verbatim and must match the format specifier count.
      if (e->callee && e->callee->kind == ast::ExprKind::Identifier &&
          e->callee->name == "print") {
        out << "printf(";
        for (std::size_t i = 0; i < e->args.size(); ++i) {
          if (i)
            out << ", ";
          if (i == 0 && e->args[i]->kind == ast::ExprKind::StringLiteral) {
            // Translate C^ format specifiers, then C-escape.
            out << "\"" << escape_c(translate_format(e->args[i]->string_value))
                << "\"";
          } else {
            emit_expr(out, e->args[i]);
          }
        }
        out << ")";
      } else {
        emit_expr(out, e->callee);
        out << "(";
        for (std::size_t i = 0; i < e->args.size(); ++i) {
          if (i)
            out << ", ";
          emit_expr(out, e->args[i]);
        }
        out << ")";
      }
      break;
    }
    case ast::ExprKind::FieldAccess:
      emit_expr(out, e->object);
      out << "." << e->field_name;
      break;
    case ast::ExprKind::IndexAccess:
      emit_expr(out, e->object);
      out << "[";
      emit_expr(out, e->index);
      out << "]";
      break;
    case ast::ExprKind::Cast:
      out << "((" << emit_type(e->cast_type) << ")";
      emit_expr(out, e->lhs);
      out << ")";
      break;
    case ast::ExprKind::Grouped:
      out << "(";
      emit_expr(out, e->lhs);
      out << ")";
      break;
    }
  }

  // escape_c turns the in-memory string body (already de-escaped by
  // the parser) into a valid C string literal: the C-escapes are
  // re-applied so the output round-trips through the C compiler
  // unchanged. Control bytes below 0x20 are hex-escaped with `\xNN`
  // so we never emit an invalid UTF-8 sequence into the C source.
  static std::string escape_c(const std::string &s) {
    std::string out;
    out.reserve(s.size() + 2);
    for (char c : s) {
      switch (c) {
      case '\n':
        out += "\\n";
        break;
      case '\t':
        out += "\\t";
        break;
      case '\r':
        out += "\\r";
        break;
      case '\\':
        out += "\\\\";
        break;
      case '"':
        out += "\\\"";
        break;
      case '\0':
        out += "\\0";
        break;
      default:
        if (static_cast<unsigned char>(c) < 0x20) {
          char buf[8];
          std::snprintf(buf, sizeof(buf), "\\x%02x",
                        static_cast<unsigned char>(c));
          out += buf;
        } else {
          out += c;
        }
      }
    }
    return out;
  }

  // translate_format: C^ -> printf format specifier translation. The
  // brace-delimited placeholders (`{}`, `{d}`, `{x}`, ...) are mapped
  // to their printf equivalents; unrecognised bodies are passed
  // through with a `%` prefix so the user gets a sensible error from
  // the C compiler rather than silent miscompilation. Brace-literal
  // escapes (e.g. `\{`) are not supported today; the design leaves
  // them for the v0.2 format-string work.
  static std::string translate_format(const std::string &s) {
    std::string out;
    out.reserve(s.size());
    std::size_t i = 0;
    while (i < s.size()) {
      if (s[i] == '{') {
        std::size_t end = s.find('}', i + 1);
        if (end == std::string::npos) {
          out += s[i++];
          continue;
        }
        std::string body = s.substr(i + 1, end - i - 1);
        // Trim
        std::size_t a = 0, b = body.size();
        while (a < b && std::isspace(static_cast<unsigned char>(body[a])))
          ++a;
        while (b > a && std::isspace(static_cast<unsigned char>(body[b - 1])))
          --b;
        body = body.substr(a, b - a);
        if (body.empty())
          out += "%s"; // {} -> generic, default to string
        else if (body == "d" || body == "i")
          out += "%d";
        else if (body == "u")
          out += "%u";
        else if (body == "x")
          out += "%x";
        else if (body == "X")
          out += "%X";
        else if (body == "s")
          out += "%s";
        else if (body == "f" || body == "F")
          out += "%f";
        else if (body == "c")
          out += "%c";
        else if (body == "p")
          out += "%p";
        else if (body == "ld")
          out += "%ld";
        else if (body == "lu")
          out += "%lu";
        else if (body == "lld" || body == "d64")
          out += "%lld";
        else if (body == "llu" || body == "u64")
          out += "%llu";
        else if (body == "z" || body == "zu")
          out += "%zu";
        else
          out += "%" + body;
        i = end + 1;
      } else {
        out += s[i++];
      }
    }
    return out;
  }
};

} // namespace

// Public entry point. The caller (main.cpp) doesn't currently pipe
// its own diagnostics engine through here — instead we keep a local
// engine inside Emitter so the lowering can record structural errors
// (missing body, unresolved type, ...) without taking a parameter.
// When the type-aware lowering lands, we'll flip this signature to
// take a borrowed engine so driver-level rendering stays unified.
EmitResult emit(const ast::TranslationUnit &unit) {
  DiagnosticsEngine local;
  Emitter e(local);
  return e.run(unit);
}
} // namespace caret::backend::c
